books = [
	{ name = 'trpl', location = 'book/src/' },
	{ location = 'cxx/book/src', name= 'cxx' },
	{ location = 'mdbook/guide/src', name = 'mdbook' },
	{ location = 'rustc-dev-guide/src', name = 'dev-guide' },
]
